#ifndef NEPTUNE_H
#define NEPTUNE_H 1

#include "images/images.h"

#define NEPTUNE_VRAM 0x1000
#define AVA_VRAM (NEPTUNE_VRAM + (NEPTUNE_SIZE / 2))
#define SPR_SIZE_16x16 0x40

#define LEVEL_WIDTH_16x16 64
#define LEVEL_HEIGHT_16x16 32

#define AVA_STATE_STANDING 0
#define AVA_STATE_FALLING 1
#define AVA_STATE_FALL_NO 2
#define AVA_STATE_ON_LADDER 3

#define AVA_SPRITE 0
#define POINTER_SPR_UP 63
#define POINTER_SPR_DOWN 62
#define POINTER_SPR_LEFT 61
#define POINTER_SPR_RIGHT 60

#define AVA_STANDING AVA_VRAM
#define AVA_WALK_1 (AVA_VRAM + SPR_SIZE_16x16)
#define AVA_WALK_2 (AVA_VRAM + (2 * SPR_SIZE_16x16))
#define AVA_JUMP (AVA_VRAM + (3 * SPR_SIZE_16x16))

const int AVA_WALK_FRAMES[] = {
    AVA_STANDING,
    AVA_STANDING,
    AVA_WALK_1,
    AVA_WALK_1,
    AVA_WALK_1,
    AVA_WALK_1,
    AVA_STANDING,
    AVA_STANDING,
    AVA_STANDING,
    AVA_STANDING,
    AVA_WALK_2,
    AVA_WALK_2,
    AVA_WALK_2,
    AVA_WALK_2,
    AVA_STANDING,
    AVA_STANDING};

#define POINTERU_VRAM (AVA_VRAM + (8 * SPR_SIZE_16x16))
#define POINTERL_VRAM (AVA_VRAM + (9 * SPR_SIZE_16x16))

#endif