#ifndef CONST_H
#define CONST_H 1

#define SPACE_EMPTY 0
#define SPACE_PHOTON 1
#define SPACE_ANTIPHOTON 2
#define SPACE_RIGHT_LEFT_MIRROR 3
#define SPACE_LEFT_RIGHT_MIRROR 4
#define SPACE_RIGHT_LEFT_SOLMIR 5
#define SPACE_LEFT_RIGHT_SOLMIR 6

#define SPACE_ANNIHILATION 255

#define PLAYER_SPRITE_1 0
#define PLAYER_SPRITE_2 1

#define MAX_PHOTONS 4

#define PHOTON_SPR_START 3
#define GRID_SPRITE_START (PHOTON_SPR_START + MAX_PHOTONS)

#define UP 0
#define DOWN 1
#define LEFT 2
#define RIGHT 3
#define DIR_NONE 4

#define ADPCM_PHOTON 0
#define ADPCM_PICKUP (ADPCM_PHOTON + PHOTON_SIZE)
#define ADPCM_WRONG (ADPCM_PICKUP + PICKUP_SIZE)
#define ADPCM_CLINK (ADPCM_WRONG + WRONG_SIZE)

#endif
