#ifndef CONST_H
#define CONST_H 1

#define SPACE_EMPTY 0
#define SPACE_PHOTON 1
#define SPACE_ANTIPHOTON 2
#define SPACE_RIGHT_LEFT_MIRROR 3
#define SPACE_LEFT_RIGHT_MIRROR 4

#define PLAYER_SPRITE_1 0
#define PLAYER_SPRITE_2 1

#define MAX_PHOTONS 4

#define PHOTON_SPR_START 2
#define GRID_SPRITE_START (PHOTON_SPR_START + MAX_PHOTONS)

#define UP 0
#define DOWN 1
#define LEFT 2
#define RIGHT 3

#endif
