#ifndef CD_H
#define CD_H 1

#define LOGO_OVERLAY 1
#define ADPCM_OVERLAY 2
#define CLASSIC_OVERLAY 3
#define CLASSIC_DATA_OVERLAY 4
#define IMAGE_OVERLAY 5
#define GOVERNOR_OVERLAY 6
#define STORY_OVERLAY 7
#define STORY_DATA_OVERLAY 8
#define BATS_OVERLAY 9

#endif