#ifndef CD_H
#define CD_H 1

#define LOGO_OVERLAY 1
#define ADPCM_OVERLAY 2
#define CLASSIC_OVERLAY 3
#define CLASSIC_DATA_OVERLAY 4
#define IMAGE_OVERLAY 5
#define GOVERNOR_OVERLAY 6
#define STORY_OVERLAY 7
#define STORY_DATA_OVERLAY 8
#define MIRROR_OVERLAY 9
#define MIRROR_DATA_OVERLAY 10
#define TITLE_OVERLAY 11
#define INTRO_OVERLAY 12
#define NEPTUNE_OVERLAY 13

#define TRACK_FANTASY_WORLD_TITLE 3
#define TRACK_EVEN_MORE_SPACELESS 4
#define TRACK_BALLAD 5
#define TRACK_EVANSSENSE 6
#define TRACK_SPACEFUL 7
#define TRACK_CHIME_2020 8
#define TRACK_IMPOSSIBLY_BOSSY 9
#define TRACK_NOTHING_IS_HOPE 10
#define TRACK_LACKED_EVEN_DAISY 11
#define TRACK_YOUR_SOUL_LAVA 12
#define TRACK_PARASOL_GENTLY 13
#define TRACK_SEVENTEEN_CROWNS 14
#define TRACK_THIS_PENANCE 15

#endif